### ISSUE TITLE
Can't use shaders.

### ISSUE THREAD

**Issue by kokoko3k** [kevinlekiller/kwin-effect-shaders#5]
I'm unable to make it work, nor i've a clue on how to debug.
I saved the 1_settings.glsl and activated some trivial filters like grayscale.
But unfortunately, upon hotkey, hothing changes on screen.
```
koko@Gozer# cat /home/koko/.config/kevinlekiller/kwin_effect_shaders.conf
[General]
AutoApply=true
Blacklist=
DefaultEnabled=true
ShaderPath=/home/koko/.local/share/kwin-effect-shaders_shaders/
Whitelist=

koko@Gozer# grep "_ENABLED 1" /home/koko/.local/share/kwin-effect-shaders_shaders/1_settings.glsl
#define FILM_NOISE_ENABLED 1
#define GRAYSCALE_ENABLED 1
```

Am i doing something wrong? Maybe the Haswell IGP is not enough?
I'm on x11, going to switch to wayland to see if something changes.

btw, i can confirm that it access the shader file because i used strace to inspect what kwin_x11 were doing when i enable the effect via the kcm interface.

**Comment by kevinlekiller** [comment]
If you installed from the AUR, it doesn't clone the shaders directory, that might be why you were missing the folder originally.

The install script checks if the directory is missing and clones it : https://github.com/kevinlekiller/kwin-effect-shaders/blob/main/install.sh#L49

**Comment by kokoko3k** [comment]
Yes, indeed, solved.
